### ISSUE TITLE
delta star in denominator

### ISSUE THREAD

**Issue by ggbioing** [ncullen93/neuroCombat#7]
According to the third equation, page 107 of the paper (y_{ijv}^{ComBat} = ...), in the denominator there should be delta_star.
In the code you put sqrt(delta_star).
Why?

https://github.com/ncullen93/neuroCombat/blob/719d432e37ab2e9b31ad3ec386fd9ac633d693b1/neuroCombat/neuroCombat.py#L262-L267

**Comment by Jfortin1** [comment]
Hi @ggbioing,

The ```delta_star``` variable in the software is actually squared (it really should be written ```delta_star_squared```,  but we followed the original ComBat code used in genomics for consistency), so the code is correct. 

By the way, our Python implementation of ComBat has not migrated to our original ComBat repo: https://github.com/Jfortin1/ComBatHarmonization.

**Comment by ggbioing** [comment]
Ok, thank you!
